### ISSUE TITLE
Gamepanic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Bluscream** [RumbleFrog/Source-Map-Thumbnails#3]
```
S:\Steam\steamapps\common\Entropy Zero\Entropy Zero\_TMP>Source-Map-Thumbnails.exe
INFO[0000] Starting game                                 Gamepanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x548aad]

goroutine 22 [running]:
github.com/rumblefrog/Source-Map-Thumbnails/queue.(*Queue_t).Terminate(0xc000050400, 0x0, 0x0)
        F:/Github/Source-Map-Thumbnails/queue/queue.go:285 +0x3d
github.com/rumblefrog/Source-Map-Thumbnails/queue.(*Queue_t).Populate(0xc000050400)
        F:/Github/Source-Map-Thumbnails/queue/queue.go:294 +0x4a0
github.com/rumblefrog/Source-Map-Thumbnails/queue.(*Queue_t).Start(0xc000050400)
        F:/Github/Source-Map-Thumbnails/queue/queue.go:41 +0x36
created by main.main
        F:/Github/Source-Map-Thumbnails/main.go:42 +0x25e
```

**Comment by Bluscream** [comment]
The issue was that i forgot to adjust the config.toml
